### PR TITLE
Manage process status

### PR DESCRIPTION
**Pull request by googlielmo**
- Process Status management
  - Enhanced `member list`
  - Fix `member stop` deletes process information
  - New `member remove` command

### CODE REVIEW

**Comment by alparslanavci** [comment]
@googlielmo it would be good to have a PR for process status implementation first, since it will not only affect the `list` command, but also some others. After implementing the process status, and also adding the unit tests for the new classes (see #32), we can work on the `list` command.

**Comment by googlielmo** [comment]
Hi @alparslanavci 
Thanks for the comment! And yes, we're on the same page here.
I hope this `Draft` PR does not cause confusion, it's just work-in-progress and will be fleshed out after process status implementation. I will ask for your kind review when it's ready.

**Comment by googlielmo** [comment]
This PR introduces Process Status management and an enhanced `member list` command.
`member stop` does not delete process information anymore (e.g., logs etc.).
A new `member remove` command has been added for that purpose.

**Comment by googlielmo** [comment]
Fixes #23 
Fixes #37

**Pull request merged**
